name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
        tox-environment:
          - django22-alchemy-mongoengine
          #- django31-alchemy-mongoengine
          #- django32-alchemy-mongoengine

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    env:
      TOXENV: ${{ matrix.tox-environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox
        
  armv64_job:
      name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
      runs-on: ubuntu-20.04
      strategy:
        fail-fast: false
        matrix:
          python-version:
            - 3.8
          tox-environment:
            - django22-alchemy-mongoengine
            #- django31-alchemy-mongoengine
            #- django32-alchemy-mongoengine
      env:
        TOXENV: ${{ matrix.tox-environment }}    
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt update && \
              apt install -y python3.8 && \
              apt install -y python3.8-venv && \
              python3.8 -m venv .env && \
              source .env/bin/activate && \
              python -m pip install --upgrade pip && \
              python -m pip install tox && \
              apt install mongodb && \
              systemctl status mongodb && \
              systemctl start mongodb && \
              python -m pip install mongoengine && \
              tox -e py38-django22-alchemy-mongoengine && \
              tox && \
              deactivate'
