name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
        tox-environment:
          - django22-alchemy-mongoengine
          #- django31-alchemy-mongoengine
          #- django32-alchemy-mongoengine

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    env:
      TOXENV: ${{ matrix.tox-environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox
        
  armv64_job:
      name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
      runs-on: ubuntu-20.04
      strategy:
        fail-fast: false
        matrix:
          python-version:
            - 3.8
          tox-environment:
            - django22-alchemy-mongoengine
            #- django31-alchemy-mongoengine
            #- django32-alchemy-mongoengine
      env:
        TOXENV: ${{ matrix.tox-environment }}    
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt update && \
              apt install -y python3.8 && \
              apt install -y python3.8-venv && \
              python3.8 -m venv .env && \
              source .env/bin/activate && \
              python -m pip install --upgrade pip && \
              python -m pip install tox && \
              #apt install -y mongodb && \
              #apt-get install -y systemd && \
              #systemctl status mongodb && \
              #service mongod status && \
              #service mongodb start && \
              apt-get update && sudo apt-get install -y lsb-release && sudo apt-get clean all && \
              wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
              apt-get install gnupg && \
              wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add - && \
              lsb_release -dc && \
              ls /etc/apt/sources.list.d/ && \
              touch /etc/apt/sources.list.d/mongodb-org-4.4.list && \
              echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
              apt-get update && \
              ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && sudo apt-get install -y tzdata && sudo dpkg-reconfigure --frontend noninteractive tzdata
              apt-get install -y mongodb-org=4.4.8 && \
              systemctl unmask mongod && \
              service mongod start && \
              service mongod status && \
              service --status-all && \
              python -m pip install mongoengine && \
              tox -e py38-django22-alchemy-mongoengine && \
              tox && \
              deactivate'
